# -*- coding: utf-8 -*-
"""app_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Bg6ffUwc95ZxkWTiUGvG8rv2UMwsm8o
"""

# -*- coding: utf-8 -*-
"""app_main.py"""

import os
import joblib
import numpy as np
import pandas as pd
import keras
import math
import traceback
from datetime import datetime, timedelta
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Optional

# 1. Importar capas personalizadas, constructor y función de tensores
from arquitectura_anfis import (
    DynamicLossWeights,
    VarietySpecificFuzzification,
    FuzzyRuleLayer,
    NormalizationLayer,
    SugenoDefuzzificationLayer_v2,
    AnfisFeatureSelector,
    MultiLRModel,
    r2_keras,
    modelo_anfis_v7_final,
    preparar_tensores_hibridos_v7_log
)

# 💡 IMPORTANTE: Importamos el motor ETL de Google Earth Engine
from gee_etl_service import GEEDataPipeline

app = FastAPI(
    title="Motor Analítico ANFIS-v7 | AgTech Inferencia Masiva",
    description="Microservicio optimizado para procesamiento por lotes con GEE integrado.",
    version="9.0"
)

#==================================================
#   DICCIONARIO DE METAS GDC
#==================================================
METAS_GDC_VARIEDAD = {
    "ACHILLEA": 1016.6,
    "AGERATHUM": 883.5,
    "AMMI MAJUS": 1003.4,
    "ASTEE": 1220.9,
    "BUPLEURUM": 765.9,
    "CHRYSANTHEMUMS SPRAY": 745.4,
    "DIANTHUS": 941.0,
    "GYPSOPHILA": 1012.8,
    "HEBE": 1757.7,
    "HELICHRYSUM": 1017.9,
    "KALE": 950.3,
    "SENECIO CINERARIA": 1422.5,
    "SOLIDAGO": 883.1,
    "SOLOMIO": 1193.1,
    "SUNFLOWER": 548.7,
    "TRACHELIUM": 879.7,
    "VERONICA": 1206.2,
    "DEFAULT": 1003.1
}

# -------------------------------------------------------------------------
# RUTAS ABSOLUTAS Y CONFIGURACIÓN
# -------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

RUTA_MODELO = os.path.join(BASE_DIR, "modelos_base", "modelo_anfis_v7_base_global.keras")
RUTA_PESOS  = os.path.join(BASE_DIR, "modelos_base", "modelo_anfis_v7_base_global.weights.h5")

SCALER_C_PATH = os.path.join(BASE_DIR, "escaladores", "scaler_clima.pkl")
SCALER_V_PATH = os.path.join(BASE_DIR, "escaladores", "scaler_siembra.pkl")
SCALER_Y_PATH = os.path.join(BASE_DIR, "escaladores", "scaler_produccion.pkl")
MAPEO_VARIEDAD_PATH = os.path.join(BASE_DIR, "escaladores", "variety_to_int.pkl")

CONFIG_EXPERTOS_PATH = os.path.join(BASE_DIR, "escaladores", "config_expertos.pkl")
REGLAS_ENCUESTA_PATH = os.path.join(BASE_DIR, "escaladores", "reglas_interaccion_encuesta.pkl")

GEE_CREDENTIALS_PATH = os.path.join(BASE_DIR, "credentials", "gee_key.json")

CLIMATE_FEATURES = ['VPD_Estres_q95_30d', 'Humedad_Agua_q5_30d', 'GDC_q95_15d', 'Intensidad_Luz_q5_30d']
PLANTING_FEATURES = ['Total_Plantas', 'GDC_Diario_Promedio', 'GDC_Acumulados_Ciclo', 'VPD_Medio_Ciclo', 'Largo promedio', 'Densidad planta promedio', '# CAMA', 'ANCHO DE CAMA']
ANFIS_INDICES = [0, 1, 2, 3]

CUSTOM_OBJECTS = {
    "DynamicLossWeights": DynamicLossWeights,
    "VarietySpecificFuzzification": VarietySpecificFuzzification,
    "FuzzyRuleLayer": FuzzyRuleLayer,
    "NormalizationLayer": NormalizationLayer,
    "SugenoDefuzzificationLayer_v2": SugenoDefuzzificationLayer_v2,
    "AnfisFeatureSelector": AnfisFeatureSelector,
    "MultiLRModel": MultiLRModel,
    "r2_keras": r2_keras
}

MODELO_CARGADO = False
gee_pipeline = None

# -------------------------------------------------------------------------
# CARGA DE ARTEFACTOS Y MODELO
# -------------------------------------------------------------------------
try:
    gee_pipeline = GEEDataPipeline(service_account_json_path=GEE_CREDENTIALS_PATH)
    print("🌍 Conexión a Google Earth Engine establecida exitosamente.")

    scaler_c = joblib.load(SCALER_C_PATH)
    scaler_v = joblib.load(SCALER_V_PATH)
    scaler_y = joblib.load(SCALER_Y_PATH)
    variety_to_int = joblib.load(MAPEO_VARIEDAD_PATH)

    config_expertos = joblib.load(CONFIG_EXPERTOS_PATH) if os.path.exists(CONFIG_EXPERTOS_PATH) else {}
    reglas_interaccion_encuesta = joblib.load(REGLAS_ENCUESTA_PATH) if os.path.exists(REGLAS_ENCUESTA_PATH) else []

    try:
        modelo_anfis = keras.models.load_model(RUTA_MODELO, custom_objects=CUSTOM_OBJECTS, compile=False)
        print("🚀 Modelo ANFIS-v7 (.keras) cargado correctamente.")
        MODELO_CARGADO = True
    except Exception as err_keras:
        print(f"⚠️ Falló la deserialización directa ({err_keras}). Ejecutando Fallback...")
        modelo_anfis = modelo_anfis_v7_final(
            num_varieties=len(variety_to_int),
            n_features=len(CLIMATE_FEATURES),
            n_non_climatic=29,
            anfis_indices=ANFIS_INDICES,
            variety_config=config_expertos,
            partial_rules=reglas_interaccion_encuesta,
            max_dias=30,
            num_mfs=3,
            fuerza_castigo=2.20
        )
        modelo_anfis.load_weights(RUTA_PESOS)
        print("✅ Pesos óptimos .weights.h5 cargados exitosamente.")
        MODELO_CARGADO = True

except Exception as e:
    print(f"❌ Error crítico inicializando artefactos: {str(e)}")


@app.get("/health")
def healthcheck():
    return {
        "status": "ok" if MODELO_CARGADO and gee_pipeline else "error",
        "modelo_cargado": MODELO_CARGADO,
        "gee_conectado": gee_pipeline is not None
    }


# -------------------------------------------------------------------------
# ESQUEMAS PYDANTIC PARA PROCESAMIENTO MASIVO
# -------------------------------------------------------------------------
class LoteCamaInput(BaseModel):
    cama_id: str
    numero_cama: float
    variedad: str
    fecha_siembra: str
    fecha_corte_historica: Optional[str] = None
    total_plantas: float
    largo_promedio: float
    densidad_planta_promedio: float
    ancho_cama: float

class LoteMasivoInput(BaseModel):
    lat: float
    lon: float
    fecha_inicio_global: str
    fecha_fin_global: str
    camas: List[LoteCamaInput]


# -------------------------------------------------------------------------
# ENDPOINT MASIVO OPTIMIZADO (UNA SOLA LLAMADA A GEE)
# -------------------------------------------------------------------------
@app.post("/api/v1/predict/lote-masivo")
def predecir_lote_masivo(payload: LoteMasivoInput):
    if not MODELO_CARGADO or not gee_pipeline:
        raise HTTPException(status_code=503, detail="Servicio no disponible.")

    try:
        # 1. 🌍 Descarga ÚNICA de GEE para toda la ventana global de la finca
        print(f"📡 Descarga única GEE global: {payload.fecha_inicio_global} a {payload.fecha_fin_global}...")
        df_c_in = gee_pipeline.extraer_clima_multidimensional_finca(
            lat=payload.lat,
            lon=payload.lon,
            fecha_inicio=payload.fecha_inicio_global,
            fecha_fin=payload.fecha_fin_global
        )

        if df_c_in.empty:
            raise HTTPException(status_code=400, detail="Google Earth Engine no devolvió datos para la ventana global.")

        df_c_in['Fecha'] = pd.to_datetime(df_c_in['Fecha'])
        resultados_lote = []
        fecha_hoy_dt = pd.to_datetime(pd.Timestamp.now(tz='America/Guayaquil').strftime('%Y-%m-%d'))

        # 2. 🔄 Procesamiento local en memoria para cada cama
        for datos in payload.camas:
            variedad_clean = datos.variedad.strip().upper()
            if variedad_clean not in variety_to_int:
                continue

            fecha_siembra_dt = pd.to_datetime(datos.fecha_siembra)

            if datos.fecha_corte_historica:
                fecha_fin_extraccion = pd.to_datetime(datos.fecha_corte_historica)
                str_fecha_corte_dinamica = datos.fecha_corte_historica
                dias_faltantes = 0
            else:
                fecha_fin_extraccion = fecha_hoy_dt
                str_fecha_corte_dinamica = None

            # Filtrar clima específico de la cama en memoria
            clima_post_siembra = df_c_in[(df_c_in['Fecha'] >= fecha_siembra_dt) & (df_c_in['Fecha'] <= fecha_fin_extraccion)]

            meta_gdc = METAS_GDC_VARIEDAD.get(variedad_clean, METAS_GDC_VARIEDAD["DEFAULT"])
            gdc_acumulado_actual = clima_post_siembra['gdc_diario'].sum() if len(clima_post_siembra) > 0 else 0.0
            gdc_diario_promedio = max(clima_post_siembra['gdc_diario'].mean() if len(clima_post_siembra) > 0 else 10.0, 1.0)

            if not datos.fecha_corte_historica:
                gdc_faltante = max(0.0, meta_gdc - gdc_acumulado_actual)
                dias_faltantes = math.ceil(gdc_faltante / gdc_diario_promedio)
                str_fecha_corte_dinamica = (fecha_fin_extraccion + timedelta(days=dias_faltantes)).strftime('%Y-%m-%d')

            porcentaje_completado = round((gdc_acumulado_actual / meta_gdc) * 100, 1)

            df_p_in = pd.DataFrame([{
                'Variedad': variedad_clean,
                'Fecha_Siembra': datos.fecha_siembra,
                'Fecha_Corte': str_fecha_corte_dinamica,
                'Total_Plantas': datos.total_plantas,
                'Largo promedio': datos.largo_promedio,
                'Densidad planta promedio': datos.densidad_planta_promedio,
                '# CAMA': datos.numero_cama,
                'ANCHO DE CAMA': datos.ancho_cama
            }])

            X_lstm_raw, X_anfis_raw, _, _, _ = preparar_tensores_hibridos_v7_log(
                df_p=df_p_in, df_c=df_c_in, variety_to_int=variety_to_int,
                climate_features=CLIMATE_FEATURES, planting_features=PLANTING_FEATURES,
                max_dias=30, modo_inferencia=True
            )

            if len(X_lstm_raw) == 0:
                continue

            sh_c = X_lstm_raw.shape
            X_lstm_scaled = scaler_c.transform(X_lstm_raw.reshape(-1, sh_c[2])).reshape(sh_c)

            num_varieties = len(variety_to_int)
            indices_para_escalar = list(range(X_anfis_raw.shape[1] - num_varieties))
            X_anfis_scaled = X_anfis_raw.copy()
            X_anfis_scaled[:, indices_para_escalar] = scaler_v.transform(X_anfis_raw[:, indices_para_escalar])

            pred_calidad_prob, pred_prod_scaled = modelo_anfis.predict([X_lstm_scaled, X_anfis_scaled], verbose=0)

            rendimiento_planta_est = np.expm1(scaler_y.inverse_transform(pred_prod_scaled.reshape(-1, 1))[0][0])
            tallos_totales = int(np.round(rendimiento_planta_est * datos.total_plantas))
            prob_calidad = float(pred_calidad_prob[0][0])

            resultados_lote.append({
                "status": "success",
                "cama_id": datos.cama_id,
                "variedad": variedad_clean,
                "fechas_fenologicas": {
                    "fecha_siembra": datos.fecha_siembra,
                    "fecha_corte_proyectada_ia": str_fecha_corte_dinamica,
                    "dias_faltantes_estimados": dias_faltantes
                },
                "estado_biologico": {
                    "gdc_meta": meta_gdc,
                    "gdc_acumulado": round(gdc_acumulado_actual, 2),
                    "porcentaje_madurez": min(porcentaje_completado, 100.0)
                },
                "prediccion_produccion": {
                    "tallos_totales_estimados": tallos_totales,
                    "rendimiento_tallos_planta": round(float(rendimiento_planta_est), 2)
                },
                "prediccion_calidad": {
                    "probabilidad_calidad_exportable": round(prob_calidad, 4),
                    "diagnostico_calidad": "EXPORTABLE" if prob_calidad >= 0.75 else "RIESGO_MERMA",
                    "alerta_temprana": "Evaluación histórica / finalizada" if datos.fecha_corte_historica else ("Evaluación temprana (<50% madurez)" if porcentaje_completado < 50 else "Evaluación madura")
                }
            })

        return {"status": "success", "total_procesados": len(resultados_lote), "resultados": resultados_lote}

    except Exception as err:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error en procesamiento masivo: {str(err)}")