# -*- coding: utf-8 -*-
"""arquitectura_anfis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Epvvr1im2QSdeBTXSo3zeLJz1u9DaoTe
"""

import numpy as np
import pandas as pd
import keras
from keras import layers, ops, regularizers
import tensorflow as tf
from tensorflow.keras.utils import pad_sequences

def modelo_anfis_v7_final(num_varieties, n_features, n_non_climatic, anfis_indices=None, variety_config=None, partial_rules=None, max_dias=30, num_mfs=3, fuerza_castigo=2.20):
    """
    ANFIS-v7: Predice Tasa de Rendimiento Unitaria Log(1 + Tallos/Planta)
    La multiplicación por Total_Plantas se ejecuta externamente en la evaluación.
    """
# Fallback defensivo si los objetos no son provistos
    if anfis_indices is None:
        anfis_indices = [0, 1, 2, 3] # Canales por defecto
    if variety_config is None:
        variety_config = {}
    if partial_rules is None:
        partial_rules = []


    input_clima = layers.Input(shape=(max_dias, n_features), name="Clima_Completo")
    input_total_v = layers.Input(shape=(n_non_climatic,), name="Variables_No_Climaticas")

    var_onehot = layers.Lambda(lambda x: x[:, -num_varieties:], name="Selector_Variedad")(input_total_v)
    variety_indices_tensor = ops.argmax(var_onehot, axis=-1)

    emb_variety = layers.Embedding(
        input_dim=num_varieties,
        output_dim=8,
        name="embedding_variedad",
        embeddings_regularizer=regularizers.l2(1e-4)
        )(variety_indices_tensor)
    emb_variety = layers.Flatten(name="aplanar_embedding")(emb_variety)
    planting_meta = layers.Lambda(lambda x: x[:, :-num_varieties], name="Meta_Datos_Siembra")(input_total_v)

    # FiLM
    gamma_cal = layers.Dense(32, activation='sigmoid', kernel_initializer='ones', name="meta_gamma_cal")(emb_variety)
    beta_cal  = layers.Dense(32, activation=None, kernel_initializer='zeros', name="meta_beta_cal")(emb_variety)

    gamma_prod = layers.Dense(64, activation='sigmoid', kernel_initializer='ones', name="meta_gamma_prod")(emb_variety)
    beta_prod  = layers.Dense(64, activation=None, kernel_initializer='zeros', name="meta_beta_prod")(emb_variety)

    # LSTM + ANFIS
    input_masked = layers.Masking(mask_value=0.0, name="enmascaramiento_clima")(input_clima)
    mask_temporal = ops.cast(ops.any(input_masked != 0.0, axis=-1), dtype="float32")

    x_lstm = layers.LSTM(32, return_sequences=False, kernel_regularizer=regularizers.l2(1e-3), name="LSTM_Climatica")(input_masked)
    x_lstm = layers.Dropout(0.30, name="dropout_lstm")(x_lstm)

    anfis_input = AnfisFeatureSelector(anfis_indices, name="filtro_clima_anfis")(input_masked)

    fuzzified = VarietySpecificFuzzification(
        num_mfs=num_mfs, num_features=len(anfis_indices), num_varieties=num_varieties,
        expert_priors=variety_config, name="Logica_Difusa"
    )([anfis_input, variety_indices_tensor])

    firing = FuzzyRuleLayer(num_mfs, len(anfis_indices), name="capa_reglas_difusas")(fuzzified)
    norm = NormalizationLayer(name="normalizacion_reglas")(firing)

    defuzz = SugenoDefuzzificationLayer_v2(
        num_mfs=num_mfs, num_features=len(anfis_indices), partial_rules=partial_rules, name="Defuzzificacion_Sujeno"
    )([anfis_input, norm])

    expanded_mask = ops.expand_dims(mask_temporal, axis=-1)
    anfis_promedio = ops.sum(defuzz * expanded_mask, axis=1) / ops.maximum(ops.sum(expanded_mask, axis=1), 1e-7)
    anfis_pico = ops.max(defuzz * expanded_mask, axis=1)

    combined = layers.Concatenate(name="fusion_global")([x_lstm, anfis_pico, anfis_promedio, planting_meta, emb_variety])

    # Rama Calidad
    x_cal = layers.Dense(32, activation='swish', kernel_regularizer=regularizers.l2(1e-3), name="quality_head_1")(combined)
    x_cal = layers.Multiply(name="film_escala_calidad")([x_cal, gamma_cal])
    x_cal = layers.Add(name="film_sesgo_calidad")([x_cal, beta_cal])
    x_cal = layers.BatchNormalization(name="batch_norm_calidad")(x_cal)
    x_cal = layers.Dropout(0.40, name="dropout_calidad")(x_cal)
    out_calidad = layers.Dense(1, activation='sigmoid', name="target_calidad")(x_cal)

    # Rama Producción Directa (Tasa Unitaria Logarítmica)
    x_prod = layers.Concatenate(name="fusion_reinyectada_produccion")([combined, planting_meta, emb_variety])
    x_prod = layers.Dense(64, activation='swish', kernel_regularizer=regularizers.l2(1e-3), name="prod_head_1")(x_prod)
    x_prod = layers.Multiply(name="film_escala_produccion")([x_prod, gamma_prod])
    x_prod = layers.Add(name="film_sesgo_produccion")([x_prod, beta_prod])
    x_prod = layers.BatchNormalization(name="batch_norm_produccion_1")(x_prod)
    x_prod = layers.Dropout(0.25, name="dropout_produccion_1")(x_prod)

    prod_residual = layers.Dense(32, activation='swish', kernel_regularizer=regularizers.l2(1e-3), name="prod_head_2")(x_prod)

    anfis_scaled = layers.Dense(32, use_bias=False, name="proyeccion_base_anfis")(anfis_promedio)
    anfis_scaled = layers.BatchNormalization(name="batch_norm_anfis_base")(anfis_scaled)

    x_final_prod = layers.Add(name="conexion_residual_produccion")([prod_residual, anfis_scaled])
    x_final_prod = layers.Dense(16, activation='swish', name="refinamiento_final_produccion")(x_final_prod)

    # Salida limpia de Tasa Unitaria Estandarizada
    out_produccion = layers.Dense(1, activation='linear', name="target_produccion")(x_final_prod)

    model = MultiLRModel(
        inputs=[input_clima, input_total_v],
        outputs=[out_calidad, out_produccion],
        penalizacion_mermas=fuerza_castigo,
        factor_prod=1.0
    )

    return model

def preparar_tensores_hibridos_v7_log(df_p, df_c, variety_to_int, climate_features, planting_features, max_dias=30, modo_inferencia=False):
    """
    Prepara tensores para ANFIS-v7.
    - En entrenamiento (modo_inferencia=False): Filtra prod <= 0 y genera etiquetas y_calidad y y_produccion.
    - En inferencia (modo_inferencia=True): No requiere Total_Produccion ni Calidad_Proporcion; solo construye tensores X_lstm y X_anfis.
    """
    X_lstm_list, X_anfis_list = [], []
    y_calidad, y_produccion = [], []
    original_indices = []

    features_locales = list(planting_features).copy()

    # Estandarización de orden estricto de columnas exógenas
    for col in ['Total_Plantas', 'GDC_Diario_Promedio', 'GDC_Acumulados_Ciclo', 'VPD_Medio_Ciclo']:
        if col in features_locales:
            features_locales.remove(col)

    features_locales.insert(0, 'VPD_Medio_Ciclo')
    features_locales.insert(0, 'GDC_Acumulados_Ciclo')
    features_locales.insert(0, 'GDC_Diario_Promedio')
    features_locales.insert(0, 'Total_Plantas')

    df_p_local = df_p.copy()
    df_c_local = df_c.copy()

    for col in ['GDC_Diario_Promedio', 'GDC_Acumulados_Ciclo', 'VPD_Medio_Ciclo']:
        if col not in df_p_local.columns:
            df_p_local[col] = 0.0

    if 'time' in df_c_local.columns:
        df_c_local = df_c_local.rename(columns={'time': 'Fecha'})

    df_p_local['Fecha_Siembra'] = pd.to_datetime(df_p_local['Fecha_Siembra'])
    df_p_local['Fecha_Corte']   = pd.to_datetime(df_p_local['Fecha_Corte'])
    df_c_local['Fecha']         = pd.to_datetime(df_c_local['Fecha'])

    # Renombrado defensivo
    for col in climate_features:
        if col not in df_c_local.columns:
            for c_real in df_c_local.columns:
                if col.split('_')[0] in c_real:
                    df_c_local = df_c_local.rename(columns={c_real: col})

    for original_index, lote in df_p_local.iterrows():
        # En modo entrenamiento se exige validación de producción
        if not modo_inferencia:
            prod_val = float(lote.get('Total_Produccion', 0.0))
            if prod_val <= 0.0 or pd.isna(prod_val):
                continue

        f_siembra = lote['Fecha_Siembra']
        f_corte   = lote['Fecha_Corte']

        mask_ciclo = (df_c_local['Fecha'] >= f_siembra) & (df_c_local['Fecha'] <= f_corte)
        clima_ciclo = df_c_local.loc[mask_ciclo]

        fecha_inicio_lstm = f_corte - pd.Timedelta(days=max_dias)
        mask_lstm = (df_c_local['Fecha'] >= fecha_inicio_lstm) & (df_c_local['Fecha'] <= f_corte)
        clima_ventana_lstm = df_c_local.loc[mask_lstm].sort_values('Fecha')[climate_features].values

        if len(clima_ventana_lstm) > 0 and len(clima_ciclo) > 0:
            X_lstm_list.append(clima_ventana_lstm)

            col_gdc = [c for c in clima_ciclo.columns if 'GDC' in str(c).upper()]
            total_gdc_ciclo = clima_ciclo[col_gdc[0]].sum() if col_gdc else 0.0

            col_vpd = [c for c in clima_ciclo.columns if 'VPD' in str(c).upper()]
            vpd_medio_ciclo = clima_ciclo[col_vpd[0]].mean() if col_vpd else 0.28

            dias_ciclo = max((f_corte - f_siembra).days, 1.0)
            tasa_gdc_diaria = total_gdc_ciclo / float(dias_ciclo)

            df_p_local.at[original_index, 'GDC_Acumulados_Ciclo'] = float(total_gdc_ciclo)
            df_p_local.at[original_index, 'GDC_Diario_Promedio']  = float(tasa_gdc_diaria)
            df_p_local.at[original_index, 'VPD_Medio_Ciclo']     = float(vpd_medio_ciclo)

            m = f_siembra.month
            s = f_siembra.isocalendar().week if hasattr(f_siembra.isocalendar(), 'week') else f_siembra.isocalendar()[1]
            tiempo_ciclico = [
                np.sin(2 * np.pi * m / 12), np.cos(2 * np.pi * m / 12),
                np.sin(2 * np.pi * s / 52), np.cos(2 * np.pi * s / 52)
            ]

            v_idx = variety_to_int[lote['Variedad']]
            one_hot_v = np.zeros(len(variety_to_int))
            one_hot_v[v_idx] = 1.0

            datos_siembra_actualizados = df_p_local.loc[original_index, features_locales].values.astype(float)
            vector_exogeno = np.concatenate([datos_siembra_actualizados, tiempo_ciclico, one_hot_v])
            X_anfis_list.append(vector_exogeno)

            if not modo_inferencia:
                proporcion_calidad_lote = float(lote['Calidad_Proporcion'])
                y_calidad.append(1.0 if proporcion_calidad_lote >= 1.0 else 0.0)
                target_prod_final = float(lote['PRODUCCION_LOG'])
                y_produccion.append(target_prod_final)

            original_indices.append(original_index)

    X_lstm_padded = pad_sequences(X_lstm_list, maxlen=max_dias, dtype='float32', padding='pre')

    return (X_lstm_padded,
            np.array(X_anfis_list).astype('float32'),
            np.array(y_calidad).astype('float32') if not modo_inferencia else None,
            np.array(y_produccion).astype('float32') if not modo_inferencia else None,
            np.array(original_indices))

import numpy as np
import keras
from keras import layers, ops, regularizers
import tensorflow as tf


# =================================================================
# 1. DEFINICIÓN DE CAPAS PERSONALIZADAS DEL BLOQUE DIFUSO (ANFIS)
# =================================================================
@keras.utils.register_keras_serializable()
class DynamicLossWeights(keras.callbacks.Callback):
    """Callback dinámico para ajustar el peso de la pérdida de producción."""
    def __init__(self, start_weight=1.0, end_weight=2.2, total_epochs=150, **kwargs):
        super().__init__(**kwargs)
        self.start_weight = float(start_weight)
        self.end_weight = float(end_weight)
        self.total_epochs = float(total_epochs)

    def on_epoch_begin(self, epoch, logs=None):
        progress = min(epoch / self.total_epochs, 1.0)
        current_weight = self.start_weight + (self.end_weight - self.start_weight) * progress

        # Asignación de pesos compatible con Keras 3 y MultiLRModel
        if hasattr(self.model, 'loss_weights'):
            self.model.loss_weights = {"target_calidad": 1.0, "target_produccion": current_weight}
        if hasattr(self.model, '_loss_weights_SaaS'):
            self.model._loss_weights_SaaS = {"target_calidad": 1.0, "target_produccion": current_weight}

    def get_config(self):
        config = super().get_config()
        config.update({
            "start_weight": self.start_weight,
            "end_weight": self.end_weight,
            "total_epochs": self.total_epochs
        })
        return config

@keras.utils.register_keras_serializable()
class VarietySpecificFuzzification(layers.Layer):
    """
    Capa de Fuzzificación corregida para ANFIS con soporte de serialización.
    """
    def __init__(self, num_mfs, num_features, num_varieties, expert_priors=None, **kwargs):
        super(VarietySpecificFuzzification, self).__init__(**kwargs)
        self.num_mfs = num_mfs
        self.num_features = num_features
        self.num_varieties = num_varieties
        self.expert_priors = expert_priors
        self.supports_masking = False

    def build(self, input_shape):
        mu_init = np.zeros((self.num_varieties, self.num_features), dtype=np.float32)
        sigma_init = np.ones((self.num_varieties, self.num_features), dtype=np.float32)

        if self.expert_priors is not None:
            ids_disponibles = sorted(list(self.expert_priors.keys()))
            for i in range(min(self.num_varieties, len(ids_disponibles))):
                v_id = ids_disponibles[i]
                params_lista = self.expert_priors[v_id]
                for j in range(min(self.num_features, len(params_lista))):
                    mu_init[i, j] = float(params_lista[j]['mu'])
                    sigma_init[i, j] = float(params_lista[j]['sigma'])

        self.mu = self.add_weight(
            name='mu',
            shape=(self.num_varieties, self.num_features),
            initializer=tf.keras.initializers.Constant(mu_init),
            trainable=True
        )

        self.sigma = self.add_weight(
            name='sigma',
            shape=(self.num_varieties, self.num_features),
            initializer=tf.keras.initializers.Constant(sigma_init),
            trainable=True
        )

        super(VarietySpecificFuzzification, self).build(input_shape)

    def call(self, inputs):
        x, v_idx = inputs
        v_idx = ops.cast(ops.reshape(v_idx, [-1]), "int32")

        batch_mu = ops.take(self.mu, v_idx, axis=0)
        batch_sigma = ops.take(self.sigma, v_idx, axis=0)

        x_expanded = ops.expand_dims(x, axis=-1)
        batch_mu_expanded = ops.expand_dims(ops.expand_dims(batch_mu, axis=1), axis=-1)
        batch_sigma_expanded = ops.expand_dims(ops.expand_dims(batch_sigma, axis=1), axis=-1)

        return ops.exp(-0.5 * ops.square((x_expanded - batch_mu_expanded) / (batch_sigma_expanded + 1e-6)))

    def get_config(self):
        # Esta función es vital para guardar/cargar el modelo
        config = super().get_config()
        config.update({
            "num_mfs": self.num_mfs,
            "num_features": self.num_features,
            "num_varieties": self.num_varieties,
            "expert_priors": self.expert_priors
        })
        return config


@keras.saving.register_keras_serializable()
class FuzzyRuleLayer(layers.Layer):
    """Evalúa la activación de las reglas difusas mediante producto cartesiano."""
    def __init__(self, num_mfs, num_features, **kwargs):
        super(FuzzyRuleLayer, self).__init__(**kwargs)
        self.num_mfs = num_mfs
        self.num_features = num_features
        self.num_rules = num_mfs ** num_features

    def call(self, inputs):
        """
        Calcula la activación de las reglas difusas mediante producto cartesiano.
        Entrada esperada: (batch_size, time_steps, num_features, num_mfs)
        Salida generada: (batch_size, time_steps, num_rules) donde num_rules = num_mfs ^ num_features
        """
        # 1. Obtener formas dinámicas (resiliente a batch sizes variables)
        s = ops.shape(inputs)
        batch_size, time_steps, num_features, num_mfs = s[0], s[1], s[2], s[3]

        # 2. Inicializar el producto cartesiano con la primera característica
        # rules tendrá forma inicial: (batch_size, time_steps, num_mfs)
        rules = inputs[:, :, 0, :]

        # 3. Iterar sobre las características restantes para completar el producto
        for i in range(1, num_features):
            # Expandimos dimensiones para preparar el producto externo
            # Reglas acumuladas: (batch_size, time_steps, reglas_actuales, 1)
            # Feature actual:    (batch_size, time_steps, 1, num_mfs)
            rules_expanded = ops.expand_dims(rules, axis=-1)
            feat_expanded = ops.expand_dims(inputs[:, :, i, :], axis=2)

            # Multiplicación broadcast (genera todas las combinaciones posibles)
            rules = rules_expanded * feat_expanded

            # 4. Aplanar las dimensiones de las reglas para la siguiente iteración
            # Resultado temporal: (batch_size, time_steps, reglas_actuales * num_mfs)
            rules = ops.reshape(rules, (batch_size, time_steps, -1))

        # 5. Verificación final de la forma de salida (batch_size, time_steps, num_rules)
        # self.num_rules debe ser igual al tamaño del último eje de 'rules'
        return rules

    def get_config(self):
        config = super(FuzzyRuleLayer, self).get_config()
        config.update({
            "num_mfs": self.num_mfs,
            "num_features": self.num_features
        })
        return config


@keras.saving.register_keras_serializable()
class NormalizationLayer(layers.Layer):
    """Aplica normalización L1 sobre las activaciones de las reglas difusas."""
    def __init__(self, **kwargs):
        super(NormalizationLayer, self).__init__(**kwargs)
        self.supports_masking = True

    def call(self, inputs):
        # Inputs shape: (batch_size, time_steps, num_rules)
        # Sum along the last axis (num_rules) and keep dimensions for broadcasting
        sum_of_rules = ops.sum(inputs, axis=-1, keepdims=True) + 1e-7
        return inputs / sum_of_rules

    def compute_mask(self, inputs, mask=None):
        return mask


@keras.saving.register_keras_serializable()
class SugenoDefuzzificationLayer_v2(layers.Layer):
    """
    Capa de Defuzzificación de Sugeno con inicialización opcional
    de reglas expertas parciales (Caja Gris).
    """
    def __init__(self, num_mfs, num_features, partial_rules=None, **kwargs):
        super(SugenoDefuzzificationLayer_v2, self).__init__(**kwargs)
        self.num_mfs = num_mfs
        self.num_features = num_features
        self.num_rules = num_mfs ** num_features
        self.partial_rules = partial_rules
        self.supports_masking = True

    def build(self, input_shape):
        # input_shape should be (norm_weights_shape, anfis_input_shape)
        # norm_weights_shape: (batch_size, time_steps, num_rules)
        # anfis_input_shape: (batch_size, time_steps, num_features)

        # Consequent parameters for Sugeno type: linear function of inputs
        # For each rule 'k': f_k = p_k * x1 + q_k * x2 + ... + r_k
        # So we need (num_rules, num_features + 1) for the coefficients (p, q, ..., r)
        # where the +1 is for the constant term 'r_k'.
        initial_consequents_coeffs = np.zeros((self.num_rules, self.num_features + 1), dtype=np.float32)

        # Initialize constant terms (last column) with 0.5 (or any sensible default)
        initial_consequents_coeffs[:, -1] = 0.5

        if self.partial_rules:
            # Apply expert priors to the constant term of the consequents
            for rule_idx in range(self.num_rules):
                # Decode rule_idx back to MF combination
                # e.g., for 3 MFs and 2 features (00, 01, 02, 10, ...)
                combination = []
                temp_idx = rule_idx
                for _ in range(self.num_features): # Iterate in reverse order of features
                    combination.insert(0, temp_idx % self.num_mfs)
                    temp_idx //= self.num_mfs

                for rule in self.partial_rules:
                    match = True
                    for feat_idx_rule, target_mf in rule['indices'].items():
                        if combination[feat_idx_rule] != target_mf: # Check if this combination matches partial rule
                            match = False
                            break
                    if match:
                        # Apply the impact to the constant term of the consequent
                        initial_consequents_coeffs[rule_idx, -1] = rule['impacto']

        self.consequents_coeffs = self.add_weight(
            name="consequents_coeffs",
            shape=(self.num_rules, self.num_features + 1),
            initializer=keras.initializers.Constant(initial_consequents_coeffs),
            trainable=True
        )
        super(SugenoDefuzzificationLayer_v2, self).build(input_shape)

    def call(self, inputs):
        # Inputs are (anfis_input, norm_weights)
        # anfis_input: (batch_size, time_steps, num_features) - These are the crisp inputs
        # norm_weights: (batch_size, time_steps, num_rules)
        anfis_input_crisp, norm_weights = inputs

        # Add a bias term (constant 1) to the crisp inputs for the constant coefficient 'r_k'
        # anfis_input_crisp_biased shape: (batch_size, time_steps, num_features + 1)
        bias_term = ops.ones_like(anfis_input_crisp[:, :, :1]) # (batch_size, time_steps, 1)
        anfis_input_crisp_biased = ops.concatenate([anfis_input_crisp, bias_term], axis=-1)

        # Calculate f_k for each rule:
        # f_k = (anfis_input_crisp_biased @ self.consequents_coeffs_k)
        # This operation is equivalent to (batch_size, time_steps, 1, num_features + 1) @ (1, num_features + 1, num_rules)
        # resulting in (batch_size, time_steps, 1, num_rules)

        # f_k will have shape (batch_size, time_steps, num_rules)
        # Each f_k is a linear combination of inputs for a specific rule
        # We need to compute f_k for all rules simultaneously
        f_k_values = ops.einsum('btf,rk->btr', anfis_input_crisp_biased, self.consequents_coeffs) # b:batch, t:time, f:features+bias, r:rules

        # Defuzzification: Sum(w_k_normalizado * f_k)
        # Result shape: (batch_size, time_steps, 1)
        output = ops.sum(norm_weights * f_k_values, axis=-1, keepdims=True)

        return output

    def compute_mask(self, inputs, mask=None):
        # The mask should be for the time_steps dimension, taken from anfis_input_crisp
        if mask is not None and isinstance(mask, (list, tuple)):
            # The first input (anfis_input_crisp) is typically masked
            return mask[0]
        return None

    def get_config(self):
        config = super(SugenoDefuzzificationLayer_v2, self).get_config()
        config.update({
            "num_mfs": self.num_mfs,
            "num_features": self.num_features,
            "partial_rules": self.partial_rules
        })
        return config


@keras.utils.register_keras_serializable(package="AgroTechFloricola")
class AnfisFeatureSelector(layers.Layer):
    """
    Selecciona los índices climáticos para el bloque ANFIS manteniendo
    intacta la máscara temporal de Keras 3.
    """
    def __init__(self, indices, **kwargs):
        super().__init__(**kwargs)
        self.indices = list(indices)
        self.supports_masking = True

    def call(self, inputs):
        return ops.take(inputs, self.indices, axis=-1)

    def compute_mask(self, inputs, mask=None):
        return mask

    def get_config(self):
        config = super().get_config()
        config.update({"indices": self.indices})
        return config


# =================================================================
# 2. MODELO MULTI-TAREA CON TRAIN_STEP Y TEST_STEP INTEGRADOS
# =================================================================
@keras.saving.register_keras_serializable(package="AgroTechFloricola")
class MultiLRModel(keras.Model):
    def __init__(self, inputs=None, outputs=None, penalizacion_mermas=2.20, factor_prod=1.0, **kwargs):
        super().__init__(inputs=inputs, outputs=outputs, **kwargs)
        self.penalizacion_mermas = float(penalizacion_mermas)
        self.factor_prod = float(factor_prod)
        self._loss_weights_SaaS = {"target_calidad": 1.0, "target_produccion": 1.0}

        self._bce_SaaS = keras.losses.BinaryCrossentropy(reduction=None)
        self._huber_SaaS = keras.losses.Huber(delta=1.0, reduction=None)

        self.loss_tracker = keras.metrics.Mean(name="loss")
        self.loss_cal_tracker = keras.metrics.Mean(name="loss_calidad")
        self.loss_prod_tracker = keras.metrics.Mean(name="loss_produccion")

    @property
    def metrics(self):
        return [self.loss_tracker, self.loss_cal_tracker, self.loss_prod_tracker] + super().metrics

    def _calcular_loss_colectiva(self, x, y_true, y_pred, sample_weight=None):
        p_cal = y_pred[0] if isinstance(y_pred, (list, tuple)) else y_pred
        p_prod = y_pred[1] if isinstance(y_pred, (list, tuple)) else y_pred

        pred_calidad = ops.reshape(p_cal, [-1, 1])
        pred_produccion = ops.reshape(p_prod, [-1, 1])

        if isinstance(y_true, dict):
            real_calidad = ops.reshape(y_true["target_calidad"], [-1, 1])
            real_produccion = ops.reshape(y_true["target_produccion"], [-1, 1])
        else:
            real_calidad = ops.reshape(y_true[0], [-1, 1])
            real_produccion = ops.reshape(y_true[1], [-1, 1])

        # 1. Pérdida Calidad Balanceada
        loss_cal_raw = self._bce_SaaS(real_calidad, pred_calidad)
        mascara_mermas = ops.cast(ops.equal(real_calidad, 0.0), dtype="float32")
        mascara_perfectos = ops.cast(ops.equal(real_calidad, 1.0), dtype="float32")
        factor_ponderado = (mascara_mermas * self.penalizacion_mermas) + (mascara_perfectos * 1.0)

        loss_cal_vector = loss_cal_raw * factor_ponderado

        # 2. Pérdida Producción Huber Asimétrica
        residual = real_produccion - pred_produccion
        loss_prod_raw = self._huber_SaaS(real_produccion, pred_produccion)

        pesos_pico = ops.where(residual > 0.0, 1.40, 1.00)

        meta_vars = x[1] if isinstance(x, (list, tuple)) else x
        total_plantas = ops.reshape(meta_vars[:, 0], [-1, 1])
        peso_lote = ops.clip(total_plantas / ops.maximum(ops.mean(total_plantas), 1.0), 0.5, 2.0)

        loss_prod_vector = loss_prod_raw * pesos_pico * peso_lote * self.factor_prod

        # -----------------------------------------------------------------
        # 💡 APLICACIÓN DE SAMPLE WEIGHTS POR VARIEDAD (SI EXISTEN)
        # -----------------------------------------------------------------
        if sample_weight is not None:
            if isinstance(sample_weight, dict):
                if "target_calidad" in sample_weight:
                    sw_cal = ops.reshape(sample_weight["target_calidad"], [-1, 1])
                    loss_cal_vector = loss_cal_vector * sw_cal
                if "target_produccion" in sample_weight:
                    sw_prod = ops.reshape(sample_weight["target_produccion"], [-1, 1])
                    loss_prod_vector = loss_prod_vector * sw_prod
            else:
                sw_general = ops.reshape(sample_weight, [-1, 1])
                loss_prod_vector = loss_prod_vector * sw_general

        loss_calidad_balanceada = ops.mean(loss_cal_vector)
        loss_produccion_final = ops.mean(loss_prod_vector)

        w_cal = float(self._loss_weights_SaaS.get("target_calidad", 1.0))
        w_prod = float(self._loss_weights_SaaS.get("target_produccion", 1.0))

        total_loss = (w_cal * loss_calidad_balanceada) + (w_prod * loss_produccion_final)
        return total_loss, loss_calidad_balanceada, loss_produccion_final, real_calidad, pred_calidad, real_produccion, pred_produccion

    def train_step(self, data):
        # -----------------------------------------------------------------
        # DESEMPAQUETADO DEFENSIVO SOPTORTANDO SAMPLE WEIGHTS
        # -----------------------------------------------------------------
        if len(data) == 3:
            x, y, sample_weight = data
        else:
            x, y = data
            sample_weight = None

        with tf.GradientTape() as tape:
            y_pred = self(x, training=True)
            total_loss, l_cal, l_prod, r_cal, p_cal, r_prod, p_prod = self._calcular_loss_colectiva(x, y, y_pred, sample_weight=sample_weight)

        trainable_vars = self.trainable_variables
        gradients = tape.gradient(total_loss, trainable_vars)
        gradients, _ = tf.clip_by_global_norm(gradients, 1.0)
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        self.loss_tracker.update_state(total_loss)
        self.loss_cal_tracker.update_state(l_cal)
        self.loss_prod_tracker.update_state(l_prod)

        y_true_dict = {"target_calidad": r_cal, "target_produccion": r_prod}
        y_pred_dict = {"target_calidad": p_cal, "target_produccion": p_prod}

        metrics_logs = self.compute_metrics(x, y_true_dict, y_pred_dict, sample_weight=sample_weight)
        metrics_logs["loss"] = self.loss_tracker.result()
        metrics_logs["loss_calidad"] = self.loss_cal_tracker.result()
        metrics_logs["loss_produccion"] = self.loss_prod_tracker.result()
        return metrics_logs

    def test_step(self, data):
        # -----------------------------------------------------------------
        # DESEMPAQUETADO DEFENSIVO PARA VALIDACIÓN
        # -----------------------------------------------------------------
        if len(data) == 3:
            x, y, sample_weight = data
        else:
            x, y = data
            sample_weight = None

        y_pred = self(x, training=False)
        total_loss, l_cal, l_prod, r_cal, p_cal, r_prod, p_prod = self._calcular_loss_colectiva(x, y, y_pred, sample_weight=sample_weight)

        self.loss_tracker.update_state(total_loss)
        self.loss_cal_tracker.update_state(l_cal)
        self.loss_prod_tracker.update_state(l_prod)

        y_true_dict = {"target_calidad": r_cal, "target_produccion": r_prod}
        y_pred_dict = {"target_calidad": p_cal, "target_produccion": p_prod}

        metrics_logs = self.compute_metrics(x, y_true_dict, y_pred_dict, sample_weight=sample_weight)
        metrics_logs["loss"] = self.loss_tracker.result()
        metrics_logs["loss_calidad"] = self.loss_cal_tracker.result()
        metrics_logs["loss_produccion"] = self.loss_prod_tracker.result()
        return metrics_logs

    def get_config(self):
        config = super().get_config()
        config.update({
            "penalizacion_mermas": self.penalizacion_mermas,
            "factor_prod": self.factor_prod,
        })
        return config

    @classmethod
    def from_config(cls, config, custom_objects=None):
        return super().from_config(config, custom_objects=custom_objects)


def r2_keras(y_true, y_pred):
    SS_res = ops.sum(ops.square(y_true - y_pred))
    SS_tot = ops.sum(ops.square(y_true - ops.mean(y_true)))
    return (1.0 - SS_res / (ops.maximum(SS_tot, 1e-7)))