# -*- coding: utf-8 -*-
"""gee_etl_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2soIJn_1KJX35Ks-QUfYM10N-3Gmoh0
"""

import os
import ee
import numpy as np
import pandas as pd
from scipy.signal import savgol_filter
from google.oauth2 import service_account

class GEEDataPipeline:
    def __init__(self, service_account_json_path: str = None):
        """Inicialización desatendida de Google Earth Engine mediante Service Account."""
        json_key = service_account_json_path or os.getenv("GEE_SERVICE_KEY_PATH")

        try:
            ee.Initialize()
            print("✅ Sesión activa de Google Earth Engine reutilizada.")
        except Exception:
            if json_key and os.path.exists(json_key):
                credentials = service_account.Credentials.from_service_account_file(
                    json_key,
                    scopes=['https://www.googleapis.com/auth/earthengine']
                )
                ee.Initialize(credentials=credentials)
                print(f"✅ Autenticación exitosa con Service Account desde: {json_key}")
            else:
                raise FileNotFoundError(
                    f"❌ No se encontró el archivo de llaves de la Service Account en: {json_key}"
                )

    def extraer_clima_multidimensional_finca(self, lat: float, lon: float, fecha_inicio: str, fecha_fin: str) -> pd.DataFrame:
        punto = ee.Geometry.Point([lon, lat])
        finca = punto.buffer(200).bounds()

        # -----------------------------------------------------------------
        # 1. HISTORIAL EXTENDIDO (150 días previos)
        # -----------------------------------------------------------------
        f_ini_dt = pd.to_datetime(fecha_inicio)
        f_fin_dt = pd.to_datetime(fecha_fin)

        start_date = (f_ini_dt - pd.Timedelta(days=150)).strftime('%Y-%m-%d')
        end_date = f_fin_dt.strftime('%Y-%m-%d')

        print(f"📡 Buscando satélites desde {start_date} hasta {end_date}...")

        # -----------------------------------------------------------------
        # 2. PROCESAMIENTO SENTINEL-2 (Sin filtro de nubes)
        # -----------------------------------------------------------------
        def process_s2(image):
            ndvi = image.normalizedDifference(['B8', 'B4']).rename('NDVI')
            ndre = image.normalizedDifference(['B8', 'B5']).rename('Clorofila_NDRE')
            ndwi = image.normalizedDifference(['B8', 'B11']).rename('Humedad_Agua')
            luz  = image.select('B1').rename('Intensidad_Luz')
            evi  = image.expression(
                '2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))', {
                    'NIR': image.select('B8'),
                    'RED': image.select('B4'),
                    'BLUE': image.select('B2')
                }
            ).rename('EVI_Invernadero')
            return image.addBands([ndvi, ndre, ndwi, luz, evi])

        s2_col = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED') \
            .filterBounds(finca) \
            .filterDate(start_date, end_date) \
            .map(process_s2)

        # -----------------------------------------------------------------
        # 3. PROCESAMIENTO SENTINEL-1 (Radar - Polarización VH y VV)
        # -----------------------------------------------------------------
        s1_col = ee.ImageCollection('COPERNICUS/S1_GRD') \
            .filterBounds(finca) \
            .filterDate(start_date, end_date) \
            .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH')) \
            .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))

        # -----------------------------------------------------------------
        # 4. PROCESAMIENTO ERA5-LAND (Clima de Base)
        # -----------------------------------------------------------------
        def add_vpd(image):
            temp = image.select('temperature_2m').subtract(273.15)
            dew_temp = image.select('dewpoint_temperature_2m').subtract(273.15)

            es = temp.expression('0.6108 * exp(17.27 * T / (T + 237.3))', {'T': temp})
            ea = dew_temp.expression('0.6108 * exp(17.27 * T / (T + 237.3))', {'T': dew_temp})
            vpd = es.subtract(ea).rename('VPD_Estres')
            return image.addBands(vpd)

        era5_col = ee.ImageCollection('ECMWF/ERA5_LAND/DAILY_AGGR') \
            .filterBounds(finca) \
            .filterDate(start_date, end_date) \
            .map(add_vpd)

        # -----------------------------------------------------------------
        # 5. REDUCCIÓN ESPACIAL EN EL SERVIDOR (Server-Side Processing)
        # -----------------------------------------------------------------
        def get_stats_server_side(col, bands, nombre_fuente):
            try:
                def reduce_image(img):
                    stats = img.select(bands).reduceRegion(
                        reducer=ee.Reducer.mean(),
                        geometry=finca,
                        scale=30,
                        maxPixels=1e9
                    )
                    return ee.Feature(None, stats).set('time', img.get('system:time_start'))

                data = col.map(reduce_image).getInfo()['features']

                records = []
                for f in data:
                    props = f['properties']
                    # Filtrar imágenes que devolvieron nulos por estar fuera de la órbita exacta
                    if 'time' in props and props['time'] is not None:
                        if any(props.get(b) is not None for b in bands):
                            records.append(props)

                if records:
                    df = pd.DataFrame(records)
                    df['time'] = pd.to_datetime(df['time'], unit='ms')
                    print(f"   ✅ {nombre_fuente}: {len(df)} días consolidados con éxito.")
                    return df
                print(f"   ⚠️ {nombre_fuente}: Colección vacía o sin datos válidos.")
            except Exception as e:
                print(f"   ❌ Error procesando {nombre_fuente}: {str(e)}")
            return pd.DataFrame()

        df_era5 = get_stats_server_side(era5_col, ['temperature_2m', 'temperature_2m_min', 'temperature_2m_max', 'total_precipitation_sum', 'VPD_Estres'], 'ERA5-Land')
        df_s2   = get_stats_server_side(s2_col, ['NDVI', 'Clorofila_NDRE', 'Humedad_Agua', 'Intensidad_Luz', 'EVI_Invernadero'], 'Sentinel-2')
        df_s1   = get_stats_server_side(s1_col, ['VH', 'VV'], 'Sentinel-1')

        if df_era5.empty:
            raise ValueError("Fallo crítico: No se obtuvieron datos climáticos base de ERA5.")

        df_final = df_era5.copy()

        if not df_s2.empty and 'time' in df_s2.columns:
            df_final = pd.merge(df_final, df_s2, on='time', how='outer')

        if not df_s1.empty and 'time' in df_s1.columns:
            df_final = pd.merge(df_final, df_s1, on='time', how='outer')
            df_final['VH'] = pd.to_numeric(df_final['VH'], errors='coerce')
            df_final['VV'] = pd.to_numeric(df_final['VV'], errors='coerce')
            df_final['RVI_Estructura'] = df_final['VH'] / df_final['VV']
        else:
            df_final['RVI_Estructura'] = 1.50

        # Rellenar fallos absolutos
        valores_por_defecto = {
            'NDVI': 0.20, 'Clorofila_NDRE': 0.10, 'Humedad_Agua': 0.02,
            'Intensidad_Luz': 1100.0, 'EVI_Invernadero': 0.25, 'RVI_Estructura': 1.50
        }
        for col_name, val_default in valores_por_defecto.items():
            if col_name not in df_final.columns:
                df_final[col_name] = val_default

        df_final['fecha'] = pd.to_datetime(df_final['time']).dt.normalize()
        cols_base_num = ['NDVI', 'Clorofila_NDRE', 'Humedad_Agua', 'Intensidad_Luz', 'EVI_Invernadero',
                         'RVI_Estructura', 'temperature_2m', 'temperature_2m_min', 'temperature_2m_max',
                         'total_precipitation_sum', 'VPD_Estres']

        for c in cols_base_num:
            df_final[c] = pd.to_numeric(df_final[c], errors='coerce')

        # -----------------------------------------------------------------
        # INTERPOLACIÓN CRONOLÓGICA CORRECTA (Method = Time)
        # -----------------------------------------------------------------
        cols_presentes = [c for c in cols_base_num if c in df_final.columns]
        df_diario = df_final.groupby('fecha').agg({c: 'mean' for c in cols_presentes}).reset_index()

        rango_fechas = pd.date_range(start=df_diario['fecha'].min(), end=df_diario['fecha'].max(), freq='D')

        # Se establece la fecha como índice para interpolar basándose en el paso del tiempo real
        df_diario = df_diario.set_index('fecha').reindex(rango_fechas)
        df_diario[cols_presentes] = df_diario[cols_presentes].interpolate(method='time').ffill().bfill()
        df_diario = df_diario.reset_index().rename(columns={'index': 'fecha'})

        # -----------------------------------------------------------------
        # 6. CONVERSIONES TÉRMICAS Y GDC (Base 5.0)
        # -----------------------------------------------------------------
        df_diario['Temp_C']     = df_diario['temperature_2m'] - 273.15
        df_diario['Temp_C_min'] = df_diario['temperature_2m_min'] - 273.15
        df_diario['Temp_C_max'] = df_diario['temperature_2m_max'] - 273.15
        df_diario['GDC']        = (df_diario['Temp_C'] - 5.0).clip(lower=0.0)
        df_diario['Calor_Acumulado'] = df_diario['GDC'].cumsum()

        # -----------------------------------------------------------------
        # 7. LIMPIEZA Y SUAVIZADO TFM
        # -----------------------------------------------------------------
        if 'NDVI' in df_diario.columns:
            df_diario['NDVI'] = df_diario['NDVI'].clip(lower=-1, upper=1)
        if 'EVI_Invernadero' in df_diario.columns:
            df_diario['EVI_Invernadero'] = df_diario['EVI_Invernadero'].clip(lower=-1, upper=1)

        if len(df_diario) >= 7:
            df_diario['EVI_Trend']  = savgol_filter(df_diario['EVI_Invernadero'], 7, 2)
            df_diario['NDVI_Trend'] = savgol_filter(df_diario['NDVI'], 7, 2)
            df_diario['VPD_Trend']  = savgol_filter(df_diario['VPD_Estres'], 5, 1)
        else:
            df_diario['EVI_Trend']  = df_diario['EVI_Invernadero']
            df_diario['NDVI_Trend'] = df_diario['NDVI']
            df_diario['VPD_Trend']  = df_diario['VPD_Estres']

        df_diario['Cambio_Vigor'] = df_diario['EVI_Trend'].diff().fillna(0)

        # -----------------------------------------------------------------
        # 8. CÁLCULO DE CUANTILES ROLLING
        # -----------------------------------------------------------------
        df_diario = df_diario.set_index('fecha').sort_index()

        df_diario['VPD_Estres_q95_30d']   = df_diario['VPD_Estres'].rolling(window=30, min_periods=1).quantile(0.95)
        df_diario['Humedad_Agua_q5_30d']  = df_diario['Humedad_Agua'].rolling(window=30, min_periods=1).quantile(0.05)
        df_diario['GDC_q95_15d']          = df_diario['GDC'].rolling(window=15, min_periods=1).quantile(0.95)
        df_diario['Intensidad_Luz_q5_30d'] = df_diario['Intensidad_Luz'].rolling(window=30, min_periods=1).quantile(0.05)

        df_diario = df_diario.reset_index()

        # -----------------------------------------------------------------
        # 9. RECORTE DE SALIDA Y MAPEO A LA API
        # -----------------------------------------------------------------
        mask = (df_diario['fecha'] >= f_ini_dt) & (df_diario['fecha'] <= f_fin_dt)
        df_ciclo = df_diario.loc[mask].copy()

        base_clima = df_ciclo.rename(columns={
            'fecha': 'Fecha',
            'Temp_C': 'temperatura_media',
            'Intensidad_Luz': 'radiacion_solar',
            'total_precipitation_sum': 'precipitacion',
            'VPD_Estres': 'vpd_diario',
            'GDC': 'gdc_diario',
            'Calor_Acumulado': 'calor_acumulado',
            'Cambio_Vigor': 'cambio_vigor',
            'EVI_Trend': 'evi_trend'
        })

        base_clima['humedad_relativa'] = 75.0
        base_clima['Fecha'] = pd.to_datetime(base_clima['Fecha']).dt.strftime('%Y-%m-%d')

        return base_clima.reset_index(drop=True)
